### ISSUE TITLE
Error position is not highlighted when selected part of SQL is executed

### ISSUE THREAD

**Issue by ljenchik** [questdb/ui#71] opened 2022-11-27 22:07 UTC
Paste in the console

```SQL

select * from long_sequence(1)

select * from long_sequence(1) where cast(x as timestamp) = '2012-04-12T12:00:00A'


```

Select 

```

select * from long_sequence(1) where cast(x as timestamp) = '2012-04-12T12:00:00A'
```

with new line before the select line, click `Run`

Error says "invalid date" but position is not highlighted

Version 6.6.1

**Comment by argshook** [comment] 2023-01-25 14:35
Hello @ljenchik, thank you for filling the issue. Looks like it is a duplicate of #40, therefore i'm closing this one.

If you have any more details, please do feel free to post them. Thank you!

**Comment by ideoma** [comment] 2023-02-10 17:49
It's not a dupe. Use case is different

**Closed** 2023-02-10 21:35 UTC
